//! eco-gateway — the estate front door.
//!
//! Replaces the generated Caddyfile for estates that declare access control.
//! It is a plain HTTP reverse-proxy + authorization engine, all deny by
//! default:
//!
//!   - routes are declared in a gateway.json config (generated by configgen
//!     from ecompose.yml `access:` declarations)
//!   - a request that matches no route returns 404 — never a catch-all forward
//!   - `public` routes forward as-is
//!   - `auth` routes require a valid Bearer JWT whose role is authenticated
//!   - `role:<name>` routes require a valid JWT whose role claim equals <name>
//!   - the gateway verifies the token ONCE and injects `X-Eco-User:
//!     <sub>,roles=<role>` upstream, so backend services trust the edge
//!   - any client-supplied `X-Eco-User` is stripped before forwarding
//!
//! Errors are content-negotiated: API clients that ask for JSON (`Accept:
//! application/json`, or a `/api/*` path without an explicit HTML Accept) get a
//! machine-readable `{"error": ...}` body; browsers get a styled HTML page that
//! follows the Ecosphere design system. The default page is built in; an estate
//! can override it by setting `error_page` in gateway.json to a template file
//! whose `{{STATUS}}` / `{{TITLE}}` / `{{MESSAGE}}` / `{{PATH}}` / `{{ESTATE}}`
//! placeholders are substituted (configgen wires this from the estate's
//! `error_page:` declaration in ecompose.yml).
//!
//! Config comes from `GATEWAY_CONFIG` (a JSON file written by configgen); the
//! listening port from `SERVER_PORT` and the signing key from `JWT_SECRET`
//! (both injected into the service .env like any other service).
//!
//! TLS is deliberately absent: Cloudflare Tunnel terminates TLS at the edge,
//! so the gateway only ever speaks plain HTTP on a localhost-reachable port.

use axum::{
    body::Body,
    extract::State,
    http::{header, HeaderMap, Request, StatusCode},
    response::Response,
    routing::any,
    Router,
};
use axum::http::Method;
use jsonwebtoken::{decode, Algorithm, DecodingKey, Validation};
use serde::Deserialize;
use std::{collections::HashMap, net::SocketAddr, sync::Arc, sync::OnceLock};

/// Estate/project name (from gateway.json `estate`), surfaced on every
/// response as `X-Eco-Estate` so the Ecosphere Assistant extension and tooling
/// can detect that a hostname is an Eco estate.
static ESTATE: OnceLock<String> = OnceLock::new();

/// The JWT claim shape auth LXS issues (HS512). `sub` is the user id.
#[derive(Debug, Deserialize)]
struct Claims {
    sub: String,
    role: String,
}

#[derive(Debug, Clone, Deserialize)]
struct RouteRule {
    /// Path pattern. Ends with `/*` for a prefix match; otherwise exact.
    path: String,
    /// `127.0.0.1:<port>` upstream.
    upstream: String,
    /// `public` | `auth` | `role:<name>`.
    level: String,
    /// Optional path-prefix rewrite (like Caddy's `uri replace`). When the
    /// request path starts with `strip`, it is replaced with `rewrite` before
    /// forwarding — e.g. `/auth-api/*` → strip `/auth-api`, rewrite `/api`
    /// turns `/auth-api/auth/login` into `/api/auth/login` upstream.
    #[serde(default)]
    strip: String,
    #[serde(default)]
    rewrite: String,
    /// Optional session-cookie name to fall back to when no Bearer token is
    /// sent. Some estates keep the JWT in an httpOnly cookie (`assessment_token`)
    /// for page loads; the gateway reads it server-side and verifies it like a
    /// Bearer token.
    #[serde(default)]
    cookie: String,
}

#[derive(Debug, Clone, Deserialize)]
struct GatewayConfig {
    /// role name -> access level. Declared in ecompose.yml's `auth.roles`.
    roles: HashMap<String, String>,
    routes: Vec<RouteRule>,
    /// Estate/project name, written by configgen. Surfaced as the
    /// `X-Eco-Estate` response header so the Ecosphere Assistant extension
    /// (and tooling) can detect that a hostname is an Eco estate.
    #[serde(default)]
    estate: String,
    /// Optional absolute path to a custom HTML error-page template. When set,
    /// gateway-origin errors render through it (see `render_error_html`);
    /// otherwise the built-in Ecosphere default page is used.
    #[serde(default)]
    error_page: String,
}

#[derive(Clone)]
struct AppState {
    routes: Arc<Vec<RouteRule>>,
    roles: Arc<HashMap<String, String>>,
    client: reqwest::Client,
    jwt_secret: Arc<String>,
    estate: Arc<String>,
    /// Custom error-page template content (loaded at startup when configured).
    error_page: Option<String>,
}

/// The built-in error page — the Ecosphere design system, rendered for every
/// estate unless it declares its own `error_page` template. Tokens are replaced
/// by `substitute`: {{STATUS}} {{TITLE}} {{MESSAGE}} {{METHOD}} {{PATH}}
/// {{ESTATE}} {{ACTION}}. {{ACTION}} carries a recovery link for the status —
/// e.g. a "Sign in" button on 401 — and is empty when no recovery is available.
const DEFAULT_ERROR_PAGE: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{STATUS}} · {{ESTATE}}</title>
<style>
  * { box-sizing: border-box; }
  body { margin:0; min-height:100vh; display:grid; place-items:center; padding:2rem;
    font:400 16px/1.6 "Manrope", ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background:#f7f6f2; color:#17141d; -webkit-font-smoothing:antialiased; }
  .card { max-width:520px; width:100%; text-align:center; }
  .code { font:700 clamp(84px,18vw,128px)/1 "Manrope", ui-sans-serif, sans-serif;
    letter-spacing:-.05em; background:linear-gradient(135deg,#5b3fd6,#a793ff);
    -webkit-background-clip:text; background-clip:text; color:transparent; }
  h1 { margin:.5rem 0 .25rem; font-size:1.5rem; letter-spacing:-.03em; }
  p { margin:0 0 1.5rem; color:#665f6e; }
  .req { display:inline-block; max-width:100%; overflow-wrap:anywhere; margin:0 0 2rem;
    padding:.2rem .55rem; border:1px solid #ded9e1; border-radius:6px;
    background:#fff; color:#17141d; font:500 .85rem "DM Mono", ui-monospace, monospace; }
  a { display:inline-block; padding:.65rem 1.5rem; border-radius:10px;
    background:#5b3fd6; color:#fff; font-weight:700; text-decoration:none; }
  a:hover { background:#482bbd; }
  .estate { margin-top:2.5rem; font:500 11px/1 "DM Mono", ui-monospace, monospace;
    letter-spacing:.12em; text-transform:uppercase; color:#8d8493; }
  @media (prefers-color-scheme:dark) {
    body { background:#17131d; color:#f7f4f8; }
    p { color:#c6bdcc; }
    .req { border-color:#443b4c; background:#211c29; color:#f7f4f8; }
    a { background:#a793ff; color:#100d14; } a:hover { background:#c2b5ff; }
    .estate { color:#9c92a6; }
  }
</style>
</head>
<body>
  <main class="card">
    <div class="code">{{STATUS}}</div>
    <h1>{{TITLE}}</h1>
    <p>{{MESSAGE}}</p>
    <code class="req">{{METHOD}} {{PATH}}</code>
    {{ACTION}}
    <div class="estate">Ecosphere · {{ESTATE}}</div>
  </main>
</body>
</html>"#;

fn main() {
    let port: u16 = std::env::var("SERVER_PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(8080);
    let jwt_secret = std::env::var("JWT_SECRET").unwrap_or_default();
    if jwt_secret.is_empty() {
        eprintln!("[gateway] JWT_SECRET is not set. Refusing to start.");
        std::process::exit(1);
    }
    let config_path = std::env::var("GATEWAY_CONFIG").unwrap_or_default();
    if config_path.is_empty() {
        eprintln!("[gateway] GATEWAY_CONFIG is not set. Refusing to start.");
        std::process::exit(1);
    }
    let config_text = std::fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("[gateway] cannot read {config_path}: {e}"));
    let config: GatewayConfig = serde_json::from_str(&config_text)
        .unwrap_or_else(|e| panic!("[gateway] invalid {config_path}: {e}"));

    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .expect("build http client");

    let error_page = if config.error_page.is_empty() {
        None
    } else {
        match std::fs::read_to_string(&config.error_page) {
            Ok(content) => {
                println!("[gateway] using custom error page at {}", config.error_page);
                Some(content)
            }
            Err(e) => {
                eprintln!("[gateway] cannot read custom error page {} ({e}); using the built-in default", config.error_page);
                None
            }
        }
    };

    let state = AppState {
        routes: Arc::new(config.routes),
        roles: Arc::new(config.roles),
        client,
        jwt_secret: Arc::new(jwt_secret),
        estate: Arc::new(config.estate.clone()),
        error_page,
    };
    let _ = ESTATE.set(config.estate);

    let app = Router::new()
        .fallback(any(handle))
        .with_state(state);

    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    println!("[gateway] default-deny gateway listening on :{port}");
    let rt = tokio::runtime::Runtime::new().expect("tokio runtime");
    rt.block_on(async {
        let listener = tokio::net::TcpListener::bind(addr).await.expect("bind");
        axum::serve(listener, app).await.expect("serve");
    });
}

/// Longest-prefix route match. An exact path beats a wildcard prefix of the
/// same length; longer prefixes beat shorter ones. A trailing `/*` matches
/// everything under the path (`/api/auth/*`); a trailing `*` matches any path
/// that starts with the stem (`/admin*` → `/admin-dashboard`).
fn match_route<'a>(routes: &'a [RouteRule], path: &str) -> Option<&'a RouteRule> {
    let mut best: Option<(&RouteRule, usize, bool)> = None;
    for route in routes {
        let (score, exact) = if let Some(base) = route.path.strip_suffix("/*") {
            let hits = path == base || path.starts_with(&format!("{base}/"));
            if hits {
                (base.len() * 2 + 1, false)
            } else {
                continue;
            }
        } else if let Some(base) = route.path.strip_suffix('*') {
            let hits = path.starts_with(base);
            if hits {
                (base.len() * 2 + 2, false)
            } else {
                continue;
            }
        } else {
            if path == route.path {
                (route.path.len() * 2 + 100, true)
            } else {
                continue;
            }
        };
        let replace = match &best {
            None => true,
            Some((_, best_score, best_exact)) => score > *best_score || (score == *best_score && exact && !best_exact),
        };
        if replace {
            best = Some((route, score, exact));
        }
    }
    best.map(|(route, _, _)| route)
}

fn bearer_token(headers: &HeaderMap) -> Option<&str> {
    headers
        .get(header::AUTHORIZATION)?
        .to_str()
        .ok()?
        .strip_prefix("Bearer ")
}

/// Resolve the token from a Bearer header, falling back to a session cookie
/// when the route declares one (estates that keep the JWT in an httpOnly
/// cookie for page loads).
fn resolve_token(headers: &HeaderMap, cookie_name: &str) -> Option<String> {
    if let Some(bearer) = bearer_token(headers) {
        return Some(bearer.to_string());
    }
    if cookie_name.is_empty() {
        return None;
    }
    let raw = headers.get(header::COOKIE)?.to_str().ok()?;
    for pair in raw.split(';') {
        let pair = pair.trim();
        if let Some((name, value)) = pair.split_once('=') {
            if name.trim() == cookie_name && !value.trim().is_empty() {
                return Some(value.trim().to_string());
            }
        }
    }
    None
}

/// Verify the HS512 token. Returns the claims on success.
fn verify_token(secret: &str, token: &str) -> Option<Claims> {
    let validation = Validation::new(Algorithm::HS512);
    decode::<Claims>(token, &DecodingKey::from_secret(secret.as_bytes()), &validation)
        .ok()
        .map(|data| data.claims)
}

/// Is this role allowed on an `auth` route? A role is "authenticated" unless it
/// is explicitly declared with the `public` access level.
fn role_is_authenticated(roles: &HashMap<String, String>, role: &str) -> bool {
    roles.get(role).map(|level| level != "public").unwrap_or(true)
}

async fn handle(State(state): State<AppState>, request: Request<Body>) -> Response {
    // Normalize a trailing slash (except the root) so `/api/auth/login/` routes
    // the same as `/api/auth/login` and upstreams that don't declare the slash
    // still match. Forwarded with the same normalization.
    let path = request.uri().path().to_string();
    let normalized = if path.len() > 1 && path.ends_with('/') {
        path[..path.len() - 1].to_string()
    } else {
        path.clone()
    };
    let method = request.method().clone();
    let Some(route) = match_route(&state.routes, &normalized) else {
        // Undeclared path: 404, not 403 — the resource simply isn't routed in
        // this estate. Rendered per the request's content negotiation.
        return render_error(
            &state,
            request.headers(),
            &method,
            &path,
            StatusCode::NOT_FOUND,
            "no route declared for this path (deny by default)",
        );
    };

    // Authorization — verified once at the edge.
    let identity = match authorize(&state, route, request.headers()) {
        Ok(id) => id,
        Err(status) => {
            return render_error(
                &state,
                request.headers(),
                &method,
                &path,
                status,
                match status {
                    StatusCode::UNAUTHORIZED => "missing or invalid bearer token",
                    _ => "access denied for this role",
                },
            );
        }
    };

    proxy(&state, &route.upstream, &normalized, &route.strip, &route.rewrite, request, identity.as_deref()).await
}

fn authorize(state: &AppState, route: &RouteRule, headers: &HeaderMap) -> Result<Option<String>, StatusCode> {
    let level = &route.level;
    match level.as_str() {
        "public" => Ok(None),
        "auth" => {
            let token = resolve_token(headers, &route.cookie).ok_or(StatusCode::UNAUTHORIZED)?;
            let claims = verify_token(&state.jwt_secret, &token).ok_or(StatusCode::UNAUTHORIZED)?;
            if !role_is_authenticated(&state.roles, &claims.role) {
                return Err(StatusCode::FORBIDDEN);
            }
            Ok(Some(identity_header(&claims)))
        }
        _ => {
            // role:<name>
            let role_name = level.strip_prefix("role:").ok_or(StatusCode::INTERNAL_SERVER_ERROR)?;
            let token = resolve_token(headers, &route.cookie).ok_or(StatusCode::UNAUTHORIZED)?;
            let claims = verify_token(&state.jwt_secret, &token).ok_or(StatusCode::UNAUTHORIZED)?;
            if !claims.role.eq_ignore_ascii_case(role_name) {
                return Err(StatusCode::FORBIDDEN);
            }
            Ok(Some(identity_header(&claims)))
        }
    }
}

fn identity_header(claims: &Claims) -> String {
    format!("{},roles={}", claims.sub, claims.role)
}

const HOP_BY_HOP: &[&str] = &[
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "x-eco-user",
];

async fn proxy(
    state: &AppState,
    upstream: &str,
    path: &str,
    strip: &str,
    rewrite: &str,
    request: Request<Body>,
    identity: Option<&str>,
) -> Response {
    let (parts, body) = request.into_parts();
    let mut headers = parts.headers.clone();
    for h in HOP_BY_HOP {
        headers.remove(*h);
    }
    if let Some(id) = identity {
        headers.insert("x-eco-user", id.parse().unwrap());
    }
    // Keep the Authorization header so downstream services that verify the
    // token themselves (profile, storage, ...) still work unchanged.
    let body_stream = body.into_data_stream();

    // Apply the strip/rewrite prefix transform (e.g. /auth-api/* -> /api/*).
    let upstream_path = if !strip.is_empty() && path.starts_with(strip) {
        format!("{}{}", rewrite, &path[strip.len()..])
    } else {
        path.to_string()
    };

    let url = format!(
        "http://{upstream}{upstream_path}{}",
        parts.uri.query().map(|q| format!("?{q}")).unwrap_or_default()
    );

    let mut req_builder = state
        .client
        .request(parts.method.clone(), &url)
        .body(reqwest::Body::wrap_stream(body_stream));
    for (name, value) in headers.iter() {
        req_builder = req_builder.header(name, value);
    }
    let req = match req_builder.build() {
        Ok(r) => r,
        Err(e) => {
            return render_error(
                &state,
                &headers,
                &parts.method,
                path,
                StatusCode::BAD_GATEWAY,
                &format!("cannot build upstream request: {e}"),
            );
        }
    };

    match state.client.execute(req).await {
        Ok(resp) => {
            let status = resp.status();
            let mut builder = Response::builder().status(status);
            for (name, value) in resp.headers().iter() {
                let lower = name.as_str().to_ascii_lowercase();
                if !HOP_BY_HOP.contains(&lower.as_str()) {
                    builder = builder.header(name, value);
                }
            }
            add_estate_header(&mut builder);
            builder
                .body(Body::from_stream(resp.bytes_stream()))
                .unwrap_or_else(|e| deny(StatusCode::BAD_GATEWAY, &format!("bad upstream response: {e}")))
        }
        Err(e) => {
            render_error(
                &state,
                &headers,
                &parts.method,
                path,
                StatusCode::BAD_GATEWAY,
                &format!("upstream {upstream} unreachable: {e}"),
            )
        }
    }
}

/// Should an error response be JSON or HTML? API clients that explicitly ask
/// for JSON (or hit a `/api/*` path without asking for HTML) get JSON; anything
/// else gets the styled HTML page.
fn wants_json(headers: &HeaderMap, path: &str) -> bool {
    if let Some(accept) = headers.get(header::ACCEPT).and_then(|v| v.to_str().ok()) {
        let wants_json = accept.contains("application/json") || accept.contains("application/*+json");
        if wants_json {
            return true;
        }
        if accept.contains("text/html") || accept.contains("text/*") {
            return false;
        }
        // Accept: */* or empty — fall through to the path heuristic.
    }
    path.starts_with("/api/")
}

fn status_title(status: StatusCode) -> &'static str {
    match status {
        StatusCode::UNAUTHORIZED => "Unauthorized",
        StatusCode::FORBIDDEN => "Access denied",
        StatusCode::NOT_FOUND => "Not found",
        StatusCode::BAD_GATEWAY => "Bad gateway",
        StatusCode::SERVICE_UNAVAILABLE => "Service unavailable",
        _ => "Something went wrong",
    }
}

/// A human-friendly message for the HTML page. Technical detail (upstream
/// addresses, internal errors) stays in the JSON body only — never leak the
/// estate's internal topology to a public browser page.
fn friendly_message(status: StatusCode, _tech: &str) -> &'static str {
    match status {
        StatusCode::UNAUTHORIZED => "Please sign in to continue.",
        StatusCode::FORBIDDEN => "You don't have permission to view this.",
        StatusCode::NOT_FOUND => "This page doesn't exist, or it isn't exposed by this estate.",
        StatusCode::BAD_GATEWAY | StatusCode::SERVICE_UNAVAILABLE => {
            "Something on our side is temporarily unavailable. Please try again in a moment."
        }
        _ => "An unexpected error occurred.",
    }
}

/// Render a gateway-origin error, content-negotiated: JSON for API clients,
/// styled HTML for browsers.
fn render_error(
    state: &AppState,
    headers: &HeaderMap,
    method: &Method,
    path: &str,
    status: StatusCode,
    message: &str,
) -> Response {
    if wants_json(headers, path) {
        let body = serde_json::json!({ "error": message }).to_string();
        let mut builder = Response::builder()
            .status(status)
            .header(header::CONTENT_TYPE, "application/json; charset=utf-8");
        add_estate_header(&mut builder);
        return builder.body(Body::from(body)).unwrap();
    }
    let html = render_error_html(state, method, path, status, message);
    let mut builder = Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "text/html; charset=utf-8");
    add_estate_header(&mut builder);
    builder.body(Body::from(html)).unwrap()
}

/// Substitute the `{{PLACEHOLDER}}` tokens in an HTML error-page template.
/// `{{ACTION}}` renders a status-appropriate recovery link — "Sign in" on 401 —
/// and is empty for statuses with no obvious next step.
fn substitute(template: &str, status: StatusCode, title: &str, message: &str, method: &str, path: &str, estate: &str) -> String {
    let action = if status == StatusCode::UNAUTHORIZED {
        r#"<a href="/signin">Sign in</a>"#
    } else {
        ""
    };
    template
        .replace("{{STATUS}}", &status.as_u16().to_string())
        .replace("{{TITLE}}", &html_escape(title))
        .replace("{{MESSAGE}}", &html_escape(message))
        .replace("{{METHOD}}", &html_escape(method))
        .replace("{{PATH}}", &html_escape(path))
        .replace("{{ESTATE}}", &html_escape(estate))
        .replace("{{ACTION}}", action)
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn render_error_html(state: &AppState, method: &Method, path: &str, status: StatusCode, message: &str) -> String {
    let title = status_title(status);
    let friendly = friendly_message(status, message);
    let method_str = method.as_str();
    let estate = if state.estate.is_empty() { "Ecosphere" } else { &state.estate };
    // Custom template (with {{PLACEHOLDER}} tokens) or the built-in default.
    let template = state.error_page.as_deref().unwrap_or(DEFAULT_ERROR_PAGE);
    substitute(template, status, title, friendly, method_str, path, estate)
}

/// JSON-only fallback used where no request context survived (e.g. stream
/// errors deep in the proxy path).
fn deny(status: StatusCode, message: &str) -> Response {
    let body = serde_json::json!({ "error": message }).to_string();
    let mut builder = Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "application/json; charset=utf-8");
    add_estate_header(&mut builder);
    builder.body(Body::from(body)).unwrap()
}

fn add_estate_header(builder: &mut axum::http::response::Builder) {
    if let Some(estate) = ESTATE.get() {
        if !estate.is_empty() {
            if let Ok(value) = header::HeaderValue::from_str(estate) {
                if let Some(headers) = builder.headers_mut() {
                    headers.insert("x-eco-estate", value);
                }
            }
        }
    }
}
