//! eco-gateway — the estate front door.
//!
//! Replaces the generated Caddyfile for estates that declare access control.
//! It is a plain HTTP reverse-proxy + authorization engine, all deny by
//! default:
//!
//!   - routes are declared in a gateway.json config (generated by configgen
//!     from ecompose.yml `access:` declarations)
//!   - a request that matches no route returns 403 — never a catch-all forward
//!   - `public` routes forward as-is
//!   - `auth` routes require a valid Bearer JWT whose role is authenticated
//!   - `role:<name>` routes require a valid JWT whose role claim equals <name>
//!   - the gateway verifies the token ONCE and injects `X-Eco-User:
//!     <sub>,roles=<role>` upstream, so backend services trust the edge
//!   - any client-supplied `X-Eco-User` is stripped before forwarding
//!
//! Config comes from `GATEWAY_CONFIG` (a JSON file written by configgen); the
//! listening port from `SERVER_PORT` and the signing key from `JWT_SECRET`
//! (both injected into the service .env like any other service).
//!
//! TLS is deliberately absent: Cloudflare Tunnel terminates TLS at the edge,
//! so the gateway only ever speaks plain HTTP on a localhost-reachable port.

use axum::{
    body::Body,
    extract::State,
    http::{header, HeaderMap, Request, StatusCode},
    response::Response,
    routing::any,
    Router,
};
use jsonwebtoken::{decode, Algorithm, DecodingKey, Validation};
use serde::Deserialize;
use std::{collections::HashMap, net::SocketAddr, sync::Arc, sync::OnceLock};

/// Estate/project name (from gateway.json `estate`), surfaced on every
/// response as `X-Eco-Estate` so the Ecosphere Assistant extension and tooling
/// can detect that a hostname is an Eco estate.
static ESTATE: OnceLock<String> = OnceLock::new();

/// The JWT claim shape auth LXS issues (HS512). `sub` is the user id.
#[derive(Debug, Deserialize)]
struct Claims {
    sub: String,
    role: String,
}

#[derive(Debug, Clone, Deserialize)]
struct RouteRule {
    /// Path pattern. Ends with `/*` for a prefix match; otherwise exact.
    path: String,
    /// `127.0.0.1:<port>` upstream.
    upstream: String,
    /// `public` | `auth` | `role:<name>`.
    level: String,
    /// Optional path-prefix rewrite (like Caddy's `uri replace`). When the
    /// request path starts with `strip`, it is replaced with `rewrite` before
    /// forwarding — e.g. `/auth-api/*` → strip `/auth-api`, rewrite `/api`
    /// turns `/auth-api/auth/login` into `/api/auth/login` upstream.
    #[serde(default)]
    strip: String,
    #[serde(default)]
    rewrite: String,
    /// Optional session-cookie name to fall back to when no Bearer token is
    /// sent. Some estates keep the JWT in an httpOnly cookie (`assessment_token`)
    /// for page loads; the gateway reads it server-side and verifies it like a
    /// Bearer token.
    #[serde(default)]
    cookie: String,
}

#[derive(Debug, Clone, Deserialize)]
struct GatewayConfig {
    /// role name -> access level. Declared in ecompose.yml's `auth.roles`.
    roles: HashMap<String, String>,
    routes: Vec<RouteRule>,
    /// Estate/project name, written by configgen. Surfaced as the
    /// `X-Eco-Estate` response header so the Ecosphere Assistant extension
    /// (and tooling) can detect that a hostname is an Eco estate.
    #[serde(default)]
    estate: String,
}

#[derive(Clone)]
struct AppState {
    routes: Arc<Vec<RouteRule>>,
    roles: Arc<HashMap<String, String>>,
    client: reqwest::Client,
    jwt_secret: Arc<String>,
    estate: Arc<String>,
}

fn main() {
    let port: u16 = std::env::var("SERVER_PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(8080);
    let jwt_secret = std::env::var("JWT_SECRET").unwrap_or_default();
    if jwt_secret.is_empty() {
        eprintln!("[gateway] JWT_SECRET is not set. Refusing to start.");
        std::process::exit(1);
    }
    let config_path = std::env::var("GATEWAY_CONFIG").unwrap_or_default();
    if config_path.is_empty() {
        eprintln!("[gateway] GATEWAY_CONFIG is not set. Refusing to start.");
        std::process::exit(1);
    }
    let config_text = std::fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("[gateway] cannot read {config_path}: {e}"));
    let config: GatewayConfig = serde_json::from_str(&config_text)
        .unwrap_or_else(|e| panic!("[gateway] invalid {config_path}: {e}"));

    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .expect("build http client");

    let state = AppState {
        routes: Arc::new(config.routes),
        roles: Arc::new(config.roles),
        client,
        jwt_secret: Arc::new(jwt_secret),
        estate: Arc::new(config.estate.clone()),
    };
    let _ = ESTATE.set(config.estate);

    let app = Router::new()
        .fallback(any(handle))
        .with_state(state);

    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    println!("[gateway] default-deny gateway listening on :{port}");
    let rt = tokio::runtime::Runtime::new().expect("tokio runtime");
    rt.block_on(async {
        let listener = tokio::net::TcpListener::bind(addr).await.expect("bind");
        axum::serve(listener, app).await.expect("serve");
    });
}

/// Longest-prefix route match. An exact path beats a wildcard prefix of the
/// same length; longer prefixes beat shorter ones. A trailing `/*` matches
/// everything under the path (`/api/auth/*`); a trailing `*` matches any path
/// that starts with the stem (`/admin*` → `/admin-dashboard`).
fn match_route<'a>(routes: &'a [RouteRule], path: &str) -> Option<&'a RouteRule> {
    let mut best: Option<(&RouteRule, usize, bool)> = None;
    for route in routes {
        let (score, exact) = if let Some(base) = route.path.strip_suffix("/*") {
            let hits = path == base || path.starts_with(&format!("{base}/"));
            if hits {
                (base.len() * 2 + 1, false)
            } else {
                continue;
            }
        } else if let Some(base) = route.path.strip_suffix('*') {
            let hits = path.starts_with(base);
            if hits {
                (base.len() * 2 + 2, false)
            } else {
                continue;
            }
        } else {
            if path == route.path {
                (route.path.len() * 2 + 100, true)
            } else {
                continue;
            }
        };
        let replace = match &best {
            None => true,
            Some((_, best_score, best_exact)) => score > *best_score || (score == *best_score && exact && !best_exact),
        };
        if replace {
            best = Some((route, score, exact));
        }
    }
    best.map(|(route, _, _)| route)
}

fn bearer_token(headers: &HeaderMap) -> Option<&str> {
    headers
        .get(header::AUTHORIZATION)?
        .to_str()
        .ok()?
        .strip_prefix("Bearer ")
}

/// Resolve the token from a Bearer header, falling back to a session cookie
/// when the route declares one (estates that keep the JWT in an httpOnly
/// cookie for page loads).
fn resolve_token(headers: &HeaderMap, cookie_name: &str) -> Option<String> {
    if let Some(bearer) = bearer_token(headers) {
        return Some(bearer.to_string());
    }
    if cookie_name.is_empty() {
        return None;
    }
    let raw = headers.get(header::COOKIE)?.to_str().ok()?;
    for pair in raw.split(';') {
        let pair = pair.trim();
        if let Some((name, value)) = pair.split_once('=') {
            if name.trim() == cookie_name && !value.trim().is_empty() {
                return Some(value.trim().to_string());
            }
        }
    }
    None
}

/// Verify the HS512 token. Returns the claims on success.
fn verify_token(secret: &str, token: &str) -> Option<Claims> {
    let validation = Validation::new(Algorithm::HS512);
    decode::<Claims>(token, &DecodingKey::from_secret(secret.as_bytes()), &validation)
        .ok()
        .map(|data| data.claims)
}

/// Is this role allowed on an `auth` route? A role is "authenticated" unless it
/// is explicitly declared with the `public` access level.
fn role_is_authenticated(roles: &HashMap<String, String>, role: &str) -> bool {
    roles.get(role).map(|level| level != "public").unwrap_or(true)
}

async fn handle(State(state): State<AppState>, request: Request<Body>) -> Response {
    // Normalize a trailing slash (except the root) so `/api/auth/login/` routes
    // the same as `/api/auth/login` and upstreams that don't declare the slash
    // still match. Forwarded with the same normalization.
    let path = request.uri().path().to_string();
    let normalized = if path.len() > 1 && path.ends_with('/') {
        path[..path.len() - 1].to_string()
    } else {
        path.clone()
    };
    let Some(route) = match_route(&state.routes, &normalized) else {
        return deny(StatusCode::FORBIDDEN, "no route declared for this path (deny by default)");
    };

    // Authorization — verified once at the edge.
    let identity = match authorize(&state, route, request.headers()) {
        Ok(id) => id,
        Err(status) => {
            return deny(
                status,
                match status {
                    StatusCode::UNAUTHORIZED => "missing or invalid bearer token",
                    _ => "access denied for this role",
                },
            );
        }
    };

    proxy(&state, &route.upstream, &normalized, &route.strip, &route.rewrite, request, identity.as_deref()).await
}

fn authorize(state: &AppState, route: &RouteRule, headers: &HeaderMap) -> Result<Option<String>, StatusCode> {
    let level = &route.level;
    match level.as_str() {
        "public" => Ok(None),
        "auth" => {
            let token = resolve_token(headers, &route.cookie).ok_or(StatusCode::UNAUTHORIZED)?;
            let claims = verify_token(&state.jwt_secret, &token).ok_or(StatusCode::UNAUTHORIZED)?;
            if !role_is_authenticated(&state.roles, &claims.role) {
                return Err(StatusCode::FORBIDDEN);
            }
            Ok(Some(identity_header(&claims)))
        }
        _ => {
            // role:<name>
            let role_name = level.strip_prefix("role:").ok_or(StatusCode::INTERNAL_SERVER_ERROR)?;
            let token = resolve_token(headers, &route.cookie).ok_or(StatusCode::UNAUTHORIZED)?;
            let claims = verify_token(&state.jwt_secret, &token).ok_or(StatusCode::UNAUTHORIZED)?;
            if !claims.role.eq_ignore_ascii_case(role_name) {
                return Err(StatusCode::FORBIDDEN);
            }
            Ok(Some(identity_header(&claims)))
        }
    }
}

fn identity_header(claims: &Claims) -> String {
    format!("{},roles={}", claims.sub, claims.role)
}

const HOP_BY_HOP: &[&str] = &[
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "x-eco-user",
];

async fn proxy(
    state: &AppState,
    upstream: &str,
    path: &str,
    strip: &str,
    rewrite: &str,
    request: Request<Body>,
    identity: Option<&str>,
) -> Response {
    let (parts, body) = request.into_parts();
    let mut headers = parts.headers.clone();
    for h in HOP_BY_HOP {
        headers.remove(*h);
    }
    if let Some(id) = identity {
        headers.insert("x-eco-user", id.parse().unwrap());
    }
    // Keep the Authorization header so downstream services that verify the
    // token themselves (profile, storage, ...) still work unchanged.
    let body_stream = body.into_data_stream();

    // Apply the strip/rewrite prefix transform (e.g. /auth-api/* -> /api/*).
    let upstream_path = if !strip.is_empty() && path.starts_with(strip) {
        format!("{}{}", rewrite, &path[strip.len()..])
    } else {
        path.to_string()
    };

    let url = format!(
        "http://{upstream}{upstream_path}{}",
        parts.uri.query().map(|q| format!("?{q}")).unwrap_or_default()
    );

    let mut req_builder = state
        .client
        .request(parts.method, &url)
        .body(reqwest::Body::wrap_stream(body_stream));
    for (name, value) in headers.iter() {
        req_builder = req_builder.header(name, value);
    }
    let req = match req_builder.build() {
        Ok(r) => r,
        Err(e) => return deny(StatusCode::BAD_GATEWAY, &format!("cannot build upstream request: {e}")),
    };

    match state.client.execute(req).await {
        Ok(resp) => {
            let status = resp.status();
            let mut builder = Response::builder().status(status);
            for (name, value) in resp.headers().iter() {
                let lower = name.as_str().to_ascii_lowercase();
                if !HOP_BY_HOP.contains(&lower.as_str()) {
                    builder = builder.header(name, value);
                }
            }
            add_estate_header(&mut builder);
            builder
                .body(Body::from_stream(resp.bytes_stream()))
                .unwrap_or_else(|e| deny(StatusCode::BAD_GATEWAY, &format!("bad upstream response: {e}")))
        }
        Err(e) => deny(StatusCode::BAD_GATEWAY, &format!("upstream {upstream} unreachable: {e}")),
    }
}

fn deny(status: StatusCode, message: &str) -> Response {
    let body = serde_json::json!({ "error": message }).to_string();
    let mut builder = Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "application/json; charset=utf-8");
    add_estate_header(&mut builder);
    builder.body(Body::from(body)).unwrap()
}

fn add_estate_header(builder: &mut axum::http::response::Builder) {
    if let Some(estate) = ESTATE.get() {
        if !estate.is_empty() {
            if let Ok(value) = header::HeaderValue::from_str(estate) {
                if let Some(headers) = builder.headers_mut() {
                    headers.insert("x-eco-estate", value);
                }
            }
        }
    }
}
